export type Book = {
  id: string
  title: string
  author: string
  category: string
  description: string
  coverImage: string
  pdfUrl: string
  year: number
  pages: number
}

export const categories = [
  { id: "sistemas", name: "Ingeniería en Sistemas Computacionales", icon: "💻" },
  { id: "bioquimica", name: "Ingeniería Bioquímica", icon: "🧬" },
  { id: "electromecanica", name: "Ingeniería Electromecánica", icon: "⚙️" },
  { id: "gestion", name: "Ingeniería de Gestión Empresarial", icon: "📊" },
  { id: "arquitectura", name: "Arquitectura", icon: "🏛️" },
  { id: "administracion", name: "Administración", icon: "💼" },
  { id: "contador", name: "Contador Público", icon: "📑" },
]

export const books: Book[] = [
  // Ingeniería en Sistemas Computacionales
  {
    id: "1",
    title: "Algoritmos y Estructuras de Datos",
    author: "Thomas H. Cormen",
    category: "sistemas",
    description: "Fundamentos de algoritmos y estructuras de datos avanzadas.",
    coverImage: "/algorithms-data-structures-computer-science.jpg",
    pdfUrl: "/pdfs/algoritmos.pdf",
    year: 2021,
    pages: 1312,
  },
  {
    id: "2",
    title: "Bases de Datos Relacionales",
    author: "Ramez Elmasri",
    category: "sistemas",
    description: "Diseño y administración de bases de datos modernas.",
    coverImage: "/database-systems-textbook.jpg",
    pdfUrl: "/pdfs/fundamentos-bases-datos.pdf",
    year: 2020,
    pages: 1056,
  },
  {
    id: "3",
    title: "Programación Orientada a Objetos",
    author: "Grady Booch",
    category: "sistemas",
    description: "Conceptos avanzados de programación orientada a objetos.",
    coverImage: "/object-oriented-programming-book.jpg",
    pdfUrl: "/pdfs/programacion-orientada-objetos.pdf",
    year: 2019,
    pages: 654,
  },
  {
    id: "22",
    title: "Redes de Computadoras",
    author: "Andrew S. Tanenbaum",
    category: "sistemas",
    description: "Arquitectura y protocolos de redes de computadoras.",
    coverImage: "/computer-networks-book.jpg",
    pdfUrl: "https://www.rfc-editor.org/rfc/pdfrfc/rfc791.txt.pdf",
    year: 2021,
    pages: 928,
  },
  {
    id: "23",
    title: "Inteligencia Artificial",
    author: "Stuart Russell & Peter Norvig",
    category: "sistemas",
    description: "Fundamentos y aplicaciones de la inteligencia artificial.",
    coverImage: "/artificial-intelligence-textbook.jpg",
    pdfUrl: "https://www.aaai.org/Papers/AAAI/1988/AAAI88-000.pdf",
    year: 2020,
    pages: 1152,
  },
  {
    id: "24",
    title: "Desarrollo Web Full Stack",
    author: "Kyle Simpson",
    category: "sistemas",
    description: "Tecnologías modernas para desarrollo web completo.",
    coverImage: "/web-development-book.png",
    pdfUrl: "https://www.w3.org/TR/2016/REC-html51-20161101/html51.pdf",
    year: 2022,
    pages: 684,
  },
  {
    id: "25",
    title: "Seguridad Informática",
    author: "William Stallings",
    category: "sistemas",
    description: "Principios y prácticas de seguridad en sistemas.",
    coverImage: "/cybersecurity-textbook.jpg",
    pdfUrl: "https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf",
    year: 2021,
    pages: 792,
  },
  {
    id: "26",
    title: "Compiladores: Principios y Técnicas",
    author: "Alfred V. Aho",
    category: "sistemas",
    description: "Diseño e implementación de compiladores modernos.",
    coverImage: "/compiler-design-book.jpg",
    pdfUrl: "https://web.stanford.edu/class/cs143/lectures/lecture01.pdf",
    year: 2019,
    pages: 1024,
  },
  {
    id: "27",
    title: "Sistemas Operativos Modernos",
    author: "Andrew S. Tanenbaum",
    category: "sistemas",
    description: "Arquitectura y diseño de sistemas operativos.",
    coverImage: "/operating-systems-book.png",
    pdfUrl: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
    year: 2020,
    pages: 1076,
  },
  {
    id: "28",
    title: "Computación en la Nube",
    author: "Thomas Erl",
    category: "sistemas",
    description: "Arquitecturas y servicios de cloud computing.",
    coverImage: "/cloud-computing-book.jpg",
    pdfUrl: "https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-145.pdf",
    year: 2022,
    pages: 528,
  },

  // Ingeniería Bioquímica
  {
    id: "4",
    title: "Bioquímica Fundamental",
    author: "Donald Voet & Judith G. Voet",
    category: "bioquimica",
    description: "Fundamentos de bioquímica aplicada a la ingeniería.",
    coverImage: "/biochemistry-textbook.jpg",
    pdfUrl: "https://www.ncbi.nlm.nih.gov/books/NBK21154/pdf/Bookshelf_NBK21154.pdf",
    year: 2020,
    pages: 1520,
  },
  {
    id: "5",
    title: "Biotecnología Industrial",
    author: "Arnold L. Demain",
    category: "bioquimica",
    description: "Aplicaciones industriales de la biotecnología moderna.",
    coverImage: "/industrial-biotechnology-book.jpg",
    pdfUrl: "https://www.fao.org/3/y2775e/y2775e.pdf",
    year: 2021,
    pages: 892,
  },
  {
    id: "6",
    title: "Ingeniería de Bioprocesos",
    author: "Michael L. Shuler",
    category: "bioquimica",
    description: "Diseño y optimización de procesos bioquímicos.",
    coverImage: "/bioprocess-engineering-textbook.jpg",
    pdfUrl: "https://www.ncbi.nlm.nih.gov/books/NBK558906/pdf/Bookshelf_NBK558906.pdf",
    year: 2018,
    pages: 756,
  },
  {
    id: "29",
    title: "Microbiología Industrial",
    author: "Alexander Fleming",
    category: "bioquimica",
    description: "Aplicaciones de microorganismos en la industria.",
    coverImage: "/industrial-microbiology-book.jpg",
    pdfUrl: "https://www.ncbi.nlm.nih.gov/books/NBK8423/pdf/Bookshelf_NBK8423.pdf",
    year: 2020,
    pages: 864,
  },
  {
    id: "30",
    title: "Enzimología Aplicada",
    author: "Palmer Trevor",
    category: "bioquimica",
    description: "Uso de enzimas en procesos industriales.",
    coverImage: "/enzyme-engineering-book.jpg",
    pdfUrl: "https://www.ncbi.nlm.nih.gov/books/NBK22553/pdf/Bookshelf_NBK22553.pdf",
    year: 2019,
    pages: 624,
  },
  {
    id: "31",
    title: "Ingeniería Genética",
    author: "James Watson",
    category: "bioquimica",
    description: "Técnicas modernas de manipulación genética.",
    coverImage: "/genetic-engineering-textbook.jpg",
    pdfUrl: "https://www.genome.gov/sites/default/files/media/files/2020-08/Glossary.pdf",
    year: 2021,
    pages: 728,
  },
  {
    id: "32",
    title: "Biorreactores y Fermentación",
    author: "Carlos Rolz",
    category: "bioquimica",
    description: "Diseño y operación de biorreactores industriales.",
    coverImage: "/bioreactor-design-book.jpg",
    pdfUrl: "https://www.fao.org/3/x5062e/x5062e.pdf",
    year: 2020,
    pages: 596,
  },
  {
    id: "33",
    title: "Bioquímica Clínica",
    author: "William Marshall",
    category: "bioquimica",
    description: "Aplicaciones médicas de la bioquímica.",
    coverImage: "/clinical-biochemistry-book.jpg",
    pdfUrl: "https://www.ncbi.nlm.nih.gov/books/NBK279/pdf/Bookshelf_NBK279.pdf",
    year: 2021,
    pages: 892,
  },
  {
    id: "34",
    title: "Bioética en Biotecnología",
    author: "Van Rensselaer Potter",
    category: "bioquimica",
    description: "Consideraciones éticas en la biotecnología moderna.",
    coverImage: "/bioethics-textbook.jpg",
    pdfUrl: "https://unesdoc.unesco.org/ark:/48223/pf0000146180",
    year: 2019,
    pages: 468,
  },
  {
    id: "35",
    title: "Nanotecnología Biológica",
    author: "Richard Feynman",
    category: "bioquimica",
    description: "Aplicaciones de la nanotecnología en biología.",
    coverImage: "/bionanotechnology-book.jpg",
    pdfUrl: "https://www.nano.gov/sites/default/files/pub_resource/nni_strategic_plan_2016.pdf",
    year: 2022,
    pages: 536,
  },

  // Ingeniería Electromecánica
  {
    id: "7",
    title: "Sistemas Electromecánicos",
    author: "Stephen J. Chapman",
    category: "electromecanica",
    description: "Integración de sistemas eléctricos y mecánicos.",
    coverImage: "/electromechanical-systems-engineering.jpg",
    pdfUrl: "https://web.mit.edu/16.unified/www/FALL/thermodynamics/notes/node118.pdf",
    year: 2020,
    pages: 968,
  },
  {
    id: "8",
    title: "Control Automático de Procesos",
    author: "Carlos A. Smith",
    category: "electromecanica",
    description: "Sistemas de control y automatización industrial.",
    coverImage: "/automatic-process-control-textbook.jpg",
    pdfUrl: "https://www.electrical4u.com/wp-content/uploads/2020/05/Control-Systems-Engineering.pdf",
    year: 2019,
    pages: 812,
  },
  {
    id: "9",
    title: "Máquinas Eléctricas Rotativas",
    author: "A. E. Fitzgerald",
    category: "electromecanica",
    description: "Teoría y aplicación de motores y generadores.",
    coverImage: "/rotating-electrical-machines-book.jpg",
    pdfUrl:
      "https://ocw.mit.edu/courses/6-685-electric-machines-fall-2013/dd6ddb585ba069b4a8c3a17bb7c8888c_MIT6_685F13_chapter1.pdf",
    year: 2021,
    pages: 724,
  },
  {
    id: "36",
    title: "Electrónica de Potencia",
    author: "Ned Mohan",
    category: "electromecanica",
    description: "Convertidores y aplicaciones de electrónica de potencia.",
    coverImage: "/power-electronics-textbook.jpg",
    pdfUrl: "https://www.iea.org/reports/technology-roadmap-solar-photovoltaic-energy",
    year: 2021,
    pages: 756,
  },
  {
    id: "37",
    title: "Robótica Industrial",
    author: "John J. Craig",
    category: "electromecanica",
    description: "Fundamentos de robótica y automatización.",
    coverImage: "/industrial-robotics-book.jpg",
    pdfUrl: "https://www.iso.org/standard/51431.html",
    year: 2020,
    pages: 824,
  },
  {
    id: "38",
    title: "Sistemas Hidráulicos y Neumáticos",
    author: "Anthony Esposito",
    category: "electromecanica",
    description: "Diseño de sistemas de potencia fluida.",
    coverImage: "/hydraulic-systems-book.jpg",
    pdfUrl: "https://www.nfpa.org/standards-and-publications/standards",
    year: 2019,
    pages: 692,
  },
  {
    id: "39",
    title: "Mantenimiento Industrial",
    author: "Jay H. Heizer",
    category: "electromecanica",
    description: "Estrategias de mantenimiento preventivo y predictivo.",
    coverImage: "/industrial-maintenance-book.jpg",
    pdfUrl: "https://www.iso.org/standard/51431.html",
    year: 2021,
    pages: 564,
  },
  {
    id: "40",
    title: "Instrumentación Industrial",
    author: "Antonio Creus Solé",
    category: "electromecanica",
    description: "Sensores y sistemas de medición industrial.",
    coverImage: "/industrial-instrumentation-book.jpg",
    pdfUrl: "https://www.isa.org/standards-and-publications/isa-publications",
    year: 2020,
    pages: 728,
  },
  {
    id: "41",
    title: "Sistemas de Refrigeración",
    author: "Dossat Roy",
    category: "electromecanica",
    description: "Principios de refrigeración y aire acondicionado.",
    coverImage: "/refrigeration-systems-book.jpg",
    pdfUrl: "https://www.ashrae.org/technical-resources/bookstore",
    year: 2021,
    pages: 648,
  },
  {
    id: "42",
    title: "Diseño de Máquinas",
    author: "Robert L. Norton",
    category: "electromecanica",
    description: "Análisis y diseño de elementos de máquinas.",
    coverImage: "/machine-design-engineering-book.jpg",
    pdfUrl: "https://web.mit.edu/2.75/resources/random/How%20Things%20Work.pdf",
    year: 2019,
    pages: 896,
  },

  // Ingeniería de Gestión Empresarial
  {
    id: "10",
    title: "Administración Estratégica",
    author: "Fred R. David",
    category: "gestion",
    description: "Planeación estratégica y gestión empresarial moderna.",
    coverImage: "/strategic-management-business-textbook.jpg",
    pdfUrl: "https://www.un.org/en/development/desa/policy/mdg_gap/mdg_gap2015/2015GAP_FULLREPORT_EN.pdf",
    year: 2020,
    pages: 652,
  },
  {
    id: "11",
    title: "Gestión de Proyectos",
    author: "Project Management Institute",
    category: "gestion",
    description: "Metodologías y mejores prácticas en gestión de proyectos.",
    coverImage: "/project-management-guide-book.jpg",
    pdfUrl: "https://www.pmi.org/pmbok-guide-standards/foundational/pmbok",
    year: 2021,
    pages: 756,
  },
  {
    id: "12",
    title: "Innovación y Emprendimiento",
    author: "Peter F. Drucker",
    category: "gestion",
    description: "Estrategias de innovación en el mundo empresarial.",
    coverImage: "/innovation-entrepreneurship-business-book.jpg",
    pdfUrl: "https://www.oecd.org/innovation/inno/2102514.pdf",
    year: 2019,
    pages: 528,
  },
  {
    id: "43",
    title: "Cadena de Suministro",
    author: "Donald J. Bowersox",
    category: "gestion",
    description: "Logística y gestión de la cadena de suministro.",
    coverImage: "/supply-chain-management-textbook.jpg",
    pdfUrl: "https://www.wto.org/english/res_e/booksp_e/world_trade_report13_e.pdf",
    year: 2021,
    pages: 684,
  },
  {
    id: "44",
    title: "Lean Manufacturing",
    author: "James P. Womack",
    category: "gestion",
    description: "Principios de manufactura esbelta y mejora continua.",
    coverImage: "/lean-manufacturing-book.jpg",
    pdfUrl: "https://www.lean.org/whatslean/principles.cfm",
    year: 2020,
    pages: 528,
  },
  {
    id: "45",
    title: "Finanzas Corporativas",
    author: "Stephen Ross",
    category: "gestion",
    description: "Análisis financiero y toma de decisiones empresariales.",
    coverImage: "/corporate-finance-textbook.jpg",
    pdfUrl: "https://www.worldbank.org/en/publication/gfdr",
    year: 2021,
    pages: 892,
  },
  {
    id: "46",
    title: "Calidad Total y Six Sigma",
    author: "Mikel Harry",
    category: "gestion",
    description: "Metodologías de mejora de calidad en procesos.",
    coverImage: "/six-sigma-quality-book.jpg",
    pdfUrl: "https://asq.org/quality-resources/six-sigma",
    year: 2019,
    pages: 624,
  },
  {
    id: "47",
    title: "Gestión del Cambio Organizacional",
    author: "John P. Kotter",
    category: "gestion",
    description: "Liderazgo y transformación en las organizaciones.",
    coverImage: "/organizational-change-management-book.jpg",
    pdfUrl: "https://www.mckinsey.com/capabilities/people-and-organizational-performance",
    year: 2020,
    pages: 548,
  },
  {
    id: "48",
    title: "Comercio Internacional",
    author: "Paul Krugman",
    category: "gestion",
    description: "Teoría y práctica del comercio global.",
    coverImage: "/international-trade-economics-book.jpg",
    pdfUrl: "https://www.wto.org/english/res_e/publications_e/wtr_e.htm",
    year: 2021,
    pages: 756,
  },
  {
    id: "49",
    title: "Análisis de Datos para Negocios",
    author: "Thomas Davenport",
    category: "gestion",
    description: "Business intelligence y analítica de datos.",
    coverImage: "/business-data-analytics-book.jpg",
    pdfUrl: "https://www.sas.com/en_us/insights/analytics/what-is-analytics.html",
    year: 2022,
    pages: 628,
  },

  // Arquitectura
  {
    id: "13",
    title: "Diseño Arquitectónico Contemporáneo",
    author: "Francis D.K. Ching",
    category: "arquitectura",
    description: "Principios y técnicas del diseño arquitectónico moderno.",
    coverImage: "/contemporary-architectural-design-book.jpg",
    pdfUrl: "https://www.arch.columbia.edu/books/reader/77-mass-customization-and-design-democratization",
    year: 2020,
    pages: 848,
  },
  {
    id: "14",
    title: "Construcción y Materiales",
    author: "José Luis Moia",
    category: "arquitectura",
    description: "Materiales de construcción y técnicas constructivas.",
    coverImage: "/construction-materials-architecture-textbook.jpg",
    pdfUrl:
      "https://unhabitat.org/sites/default/files/download-manager-files/Sustainable%20Building%20Design%20for%20Tropical%20Climates.pdf",
    year: 2021,
    pages: 692,
  },
  {
    id: "15",
    title: "Urbanismo y Planeación",
    author: "Kevin Lynch",
    category: "arquitectura",
    description: "Teoría y práctica de la planeación urbana.",
    coverImage: "/urban-planning-architecture-book.jpg",
    pdfUrl:
      "https://unhabitat.org/sites/default/files/2020/07/final_un-habitat_-covid-19_policy_and_programme_response_framework.pdf",
    year: 2018,
    pages: 564,
  },
  {
    id: "50",
    title: "Arquitectura Sustentable",
    author: "Ken Yeang",
    category: "arquitectura",
    description: "Diseño ecológico y construcción verde.",
    coverImage: "/sustainable-architecture-green-building.jpg",
    pdfUrl: "https://www.usgbc.org/resources/leed-reference-guide-building-design-and-construction",
    year: 2021,
    pages: 724,
  },
  {
    id: "51",
    title: "Estructuras para Arquitectos",
    author: "Mario Salvadori",
    category: "arquitectura",
    description: "Análisis estructural aplicado a la arquitectura.",
    coverImage: "/structural-design-architecture-book.jpg",
    pdfUrl: "https://www.aisc.org/publications/steel-construction-manual/",
    year: 2020,
    pages: 836,
  },
  {
    id: "52",
    title: "Historia de la Arquitectura",
    author: "Banister Fletcher",
    category: "arquitectura",
    description: "Evolución de la arquitectura a través del tiempo.",
    coverImage: "/architecture-history-textbook.jpg",
    pdfUrl: "https://www.metmuseum.org/toah/hd/arch/hd_arch.htm",
    year: 2019,
    pages: 964,
  },
  {
    id: "53",
    title: "Instalaciones en Edificios",
    author: "Enrique Harper",
    category: "arquitectura",
    description: "Sistemas eléctricos, hidráulicos y sanitarios.",
    coverImage: "/building-services-engineering-book.jpg",
    pdfUrl: "https://www.ashrae.org/technical-resources/ashrae-handbook",
    year: 2021,
    pages: 748,
  },
  {
    id: "54",
    title: "Restauración Arquitectónica",
    author: "Jukka Jokilehto",
    category: "arquitectura",
    description: "Conservación y restauración del patrimonio.",
    coverImage: "/architectural-restoration-conservation.jpg",
    pdfUrl: "https://whc.unesco.org/en/conventiontext/",
    year: 2020,
    pages: 592,
  },
  {
    id: "55",
    title: "Diseño Bioclimático",
    author: "Victor Olgyay",
    category: "arquitectura",
    description: "Arquitectura adaptada al clima y medio ambiente.",
    coverImage: "/bioclimatic-design-architecture.jpg",
    pdfUrl: "https://www.energy.gov/energysaver/energy-efficient-home-design",
    year: 2021,
    pages: 628,
  },
  {
    id: "56",
    title: "Paisajismo y Arquitectura",
    author: "Roberto Burle Marx",
    category: "arquitectura",
    description: "Diseño de espacios exteriores y jardines.",
    coverImage: "/landscape-architecture-design-book.jpg",
    pdfUrl: "https://www.asla.org/ContentDetail.aspx?id=31768",
    year: 2019,
    pages: 536,
  },

  // Administración
  {
    id: "16",
    title: "Fundamentos de Administración",
    author: "Stephen P. Robbins",
    category: "administracion",
    description: "Conceptos básicos de la administración empresarial.",
    coverImage: "/business-administration-fundamentals.jpg",
    pdfUrl: "https://www.ilo.org/wcmsp5/groups/public/---ed_emp/---emp_ent/documents/publication/wcms_114006.pdf",
    year: 2020,
    pages: 624,
  },
  {
    id: "17",
    title: "Recursos Humanos Estratégicos",
    author: "Gary Dessler",
    category: "administracion",
    description: "Gestión moderna del capital humano en las organizaciones.",
    coverImage: "/strategic-human-resources-management.jpg",
    pdfUrl: "https://www.ilo.org/wcmsp5/groups/public/---dgreports/---dcomm/documents/publication/wcms_560130.pdf",
    year: 2021,
    pages: 736,
  },
  {
    id: "18",
    title: "Marketing y Ventas",
    author: "Philip Kotler",
    category: "administracion",
    description: "Estrategias de marketing en el siglo XXI.",
    coverImage: "/marketing-sales-strategy-textbook.jpg",
    pdfUrl: "https://www.ama.org/wp-content/uploads/2019/01/Marketing.pdf",
    year: 2020,
    pages: 692,
  },
  {
    id: "57",
    title: "Comportamiento Organizacional",
    author: "Stephen Robbins",
    category: "administracion",
    description: "Psicología y dinámicas en las organizaciones.",
    coverImage: "/organizational-behavior-textbook.jpg",
    pdfUrl: "https://www.shrm.org/resourcesandtools/tools-and-samples",
    year: 2020,
    pages: 684,
  },
  {
    id: "58",
    title: "Negociación y Resolución de Conflictos",
    author: "Roger Fisher",
    category: "administracion",
    description: "Técnicas de negociación efectiva y mediación.",
    coverImage: "/negotiation-conflict-resolution-book.jpg",
    pdfUrl: "https://www.pon.harvard.edu/freemium/",
    year: 2019,
    pages: 528,
  },
  {
    id: "59",
    title: "Ética Empresarial",
    author: "Manuel Velasquez",
    category: "administracion",
    description: "Responsabilidad social y ética en los negocios.",
    coverImage: "/business-ethics-book.jpg",
    pdfUrl: "https://www.unglobalcompact.org/what-is-gc/mission/principles",
    year: 2021,
    pages: 596,
  },
  {
    id: "60",
    title: "Administración de Operaciones",
    author: "Jay Heizer",
    category: "administracion",
    description: "Gestión de producción y operaciones empresariales.",
    coverImage: "/operations-management-book.jpg",
    pdfUrl: "https://www.apics.org/docs/default-source/default-document-library/apics_dictionary_2015.pdf",
    year: 2020,
    pages: 748,
  },
  {
    id: "61",
    title: "E-Commerce y Negocios Digitales",
    author: "Kenneth Laudon",
    category: "administracion",
    description: "Comercio electrónico y transformación digital.",
    coverImage: "/ecommerce-digital-business-book.jpg",
    pdfUrl: "https://unctad.org/system/files/official-document/der2019_en.pdf",
    year: 2022,
    pages: 624,
  },
  {
    id: "62",
    title: "Administración de Pequeñas Empresas",
    author: "Justin Longenecker",
    category: "administracion",
    description: "Gestión de PyMES y emprendimientos.",
    coverImage: "/small-business-management-book.jpg",
    pdfUrl: "https://www.sba.gov/sites/default/files/advocacy/2018-Small-Business-Profiles-US.pdf",
    year: 2020,
    pages: 564,
  },
  {
    id: "63",
    title: "Planificación Estratégica de Negocios",
    author: "Michael Porter",
    category: "administracion",
    description: "Ventaja competitiva y estrategia corporativa.",
    coverImage: "/business-strategic-planning-book.jpg",
    pdfUrl: "https://www.isc.hbs.edu/strategy/Pages/default.aspx",
    year: 2021,
    pages: 692,
  },

  // Contador Público
  {
    id: "19",
    title: "Contabilidad Financiera",
    author: "Gerardo Guajardo Cantú",
    category: "contador",
    description: "Fundamentos de contabilidad y estados financieros.",
    coverImage: "/financial-accounting-book.jpg",
    pdfUrl:
      "https://www.ifrs.org/content/dam/ifrs/publications/pdf-standards/english/2021/issued/part-a/conceptual-framework-for-financial-reporting.pdf",
    year: 2020,
    pages: 756,
  },
  {
    id: "20",
    title: "Auditoría Integral",
    author: "Samuel Alberto Mantilla",
    category: "contador",
    description: "Normas y procedimientos de auditoría moderna.",
    coverImage: "/integral-audit-book.jpg",
    pdfUrl: "https://www.ifac.org/system/files/publications/files/IESBA-Handbook-Code-of-Ethics-2020.pdf",
    year: 2021,
    pages: 684,
  },
  {
    id: "21",
    title: "Derecho Fiscal y Tributario",
    author: "José Pérez Chávez",
    category: "contador",
    description: "Legislación fiscal y aplicación práctica en México.",
    coverImage: "/tax-law-practice-book.jpg",
    pdfUrl: "https://www.oecd.org/tax/tax-policy/taxing-wages-brochure.pdf",
    year: 2020,
    pages: 528,
  },
  {
    id: "64",
    title: "Contabilidad de Costos",
    author: "Charles Horngren",
    category: "contador",
    description: "Sistemas de costos y control gerencial.",
    coverImage: "/cost-accounting-management-book.jpg",
    pdfUrl: "https://www.imanet.org/insights-and-trends/the-future-of-management-accounting",
    year: 2020,
    pages: 824,
  },
  {
    id: "65",
    title: "Normas Internacionales de Información Financiera",
    author: "IASB",
    category: "contador",
    description: "NIIF y su aplicación práctica.",
    coverImage: "/international-financial-reporting-standards-book.jpg",
    pdfUrl: "https://www.ifrs.org/issued-standards/list-of-standards/",
    year: 2021,
    pages: 968,
  },
  {
    id: "66",
    title: "Contabilidad Administrativa",
    author: "David Noel Ramírez",
    category: "contador",
    description: "Información contable para la toma de decisiones.",
    coverImage: "/administrative-accounting-book.jpg",
    pdfUrl: "https://www.aicpa.org/research/standards.html",
    year: 2020,
    pages: 692,
  },
  {
    id: "67",
    title: "Auditoría Forense y Detección de Fraudes",
    author: "Rodrigo Estupiñán",
    category: "contador",
    description: "Técnicas de investigación contable y prevención de fraudes.",
    coverImage: "/forensic-audit-fraud-detection-book.jpg",
    pdfUrl: "https://www.acfe.com/fraud-resources.aspx",
    year: 2021,
    pages: 628,
  },
  {
    id: "68",
    title: "Finanzas Públicas",
    author: "Harvey Rosen",
    category: "contador",
    description: "Economía del sector público y políticas fiscales.",
    coverImage: "/public-finance-book.jpg",
    pdfUrl: "https://www.imf.org/external/pubs/ft/gfs/manual/pdf/all.pdf",
    year: 2019,
    pages: 748,
  },
  {
    id: "69",
    title: "Contabilidad Gubernamental",
    author: "CONAC",
    category: "contador",
    description: "Sistema de contabilidad para el sector público.",
    coverImage: "/government-accounting-book.jpg",
    pdfUrl: "https://www.conac.gob.mx/es/CONAC/Marco_Conceptual",
    year: 2020,
    pages: 584,
  },
  {
    id: "70",
    title: "Planeación Fiscal",
    author: "Enrique Calvo Nicolau",
    category: "contador",
    description: "Estrategias legales de optimización fiscal.",
    coverImage: "/fiscal-planning-book.jpg",
    pdfUrl: "https://www.oecd.org/tax/beps/",
    year: 2021,
    pages: 636,
  },
]
